server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  data:
    mongodb:
      uri: mongodb+srv://admin:zzz1234@playcluster.a1hqkve.mongodb.net/Playbours?retryWrites=true&w=majority